apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: colorlamps.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: ColorLamp
    listKind: ColorLampList
    plural: colorlamps
    singular: colorlamp
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              control:
                properties:
                  brightness:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                  hue:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                  power:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                  saturation:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                type: object
              obs:
                properties:
                  reason:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
