apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samplelakes.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: SampleLake
    listKind: SampleLakeList
    plural: samplelakes
    singular: samplelake
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              data:
                properties:
                  input:
                    properties:
                      url:
                        type: string
                    type: object
                  output:
                    properties:
                      occupied:
                        type: boolean
                    type: object
                type: object
              obs:
                properties:
                  reason:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
