apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer
  namespace: default  # XXX move to ns dspace or meta-actor

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: syncer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [create, delete, get, list, patch, update, watch]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: syncer
subjects:
  - kind: ServiceAccount
    name: syncer
    namespace: default  # XXX ditto
roleRef:
  kind: ClusterRole
  name: syncer
  apiGroup: rbac.authorization.k8s.io
