apiVersion: v1
kind: ServiceAccount
metadata:
  name: policer
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: policer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [create, delete, get, list, patch, update, watch]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policer
subjects:
  - kind: ServiceAccount
    name: policer
    namespace: default
roleRef:
  kind: ClusterRole
  name: policer
  apiGroup: rbac.authorization.k8s.io
