apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imitations.digi.dev
spec:
  group: digi.dev
  names:
    kind: Imitation
    listKind: ImitationList
    plural: imitations
    singular: imitation
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              data:
                properties:
                  input:
                    properties:
                      action:
                        type: object
                      state:
                        type: object
                    type: object
                  output:
                    properties:
                      action:
                        type: string
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
