apiVersion: digi.dev/v1
kind: YieldPolicy
metadata:
  name: example-yieldpolicy
spec:
  source:
    kind:
      group: digi.dev
      version: v1
      name: MockRoom
    name: mock-room
    namespace: default
  target:
    kind:
      group: digi.dev
      version: v1
      name: MockEmergencyAppliance
    name: mock-emerg-app
    namespace: default
  condition: "if (.source.spec.mode == \"emergency\") then true else false end"

