apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fans.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: Fan
    listKind: FanList
    plural: fans
    singular: fan
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              control:
                properties:
                  mode:
                    properties:
                      intent:
                        type: string
                      status:
                        type: string
                    type: object
                  power:
                    properties:
                      intent:
                        type: string
                      status:
                        type: string
                    type: object
                  speed:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                type: object
              obs:
                properties:
                  reason:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
