apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: measures.bench.digi.dev
spec:
  group: bench.digi.dev
  names:
    kind: Measure
    listKind: MeasureList
    plural: measures
    singular: measure
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              obs:
                properties:
                  backward_leaf:
                    type: number
                  backward_root:
                    type: number
                  forward_leaf:
                    type: number
                  forward_root:
                    type: number
                type: object
            type: object
        type: object
    served: true
    storage: true
