apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: irds.digi.dev
spec:
  group: digi.dev
  names:
    kind: Ird
    listKind: IrdList
    plural: irds
    singular: ird
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              mount:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
    served: true
    storage: true
